name: 'Excavator'

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update ca-certificate
        run: sudo update-ca-certificates
      - name: Excavate
        uses: kidonng/Scoop-GithubActions@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
